### ISSUE TITLE
TypeError: Cannot read property 'lang' of null

### ISSUE THREAD

**Issue by Aszzo** [rstackjs/rspack-vue-loader#9]
In [this code](https://github.com/rspack-contrib/rspack-vue-loader/blob/v15/lib/index.js#L120), is it necessary to make a non-null judgment on the script?
I encountered an error when using the setup syntax(`Cannot read property 'lang' of null`).

**Comment by jeromehan** [comment]
@Aszzo  You can directly use vue-loader@15.11.1,

**Comment by Aszzo** [comment]
@jeromehan thanks,i'll try it
